//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoshHub.ServicePoshHub {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePoshHub.IServicePoshHub", CallbackContract=typeof(PoshHub.ServicePoshHub.IServicePoshHubCallback))]
    public interface IServicePoshHub {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePoshHub/Connect", ReplyAction="http://tempuri.org/IServicePoshHub/ConnectResponse")]
        int Connect(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePoshHub/Connect", ReplyAction="http://tempuri.org/IServicePoshHub/ConnectResponse")]
        System.Threading.Tasks.Task<int> ConnectAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePoshHub/Disconnect", ReplyAction="http://tempuri.org/IServicePoshHub/DisconnectResponse")]
        void Disconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePoshHub/Disconnect", ReplyAction="http://tempuri.org/IServicePoshHub/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePoshHub/SelectionOfClothes", ReplyAction="http://tempuri.org/IServicePoshHub/SelectionOfClothesResponse")]
        void SelectionOfClothes(string sample, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePoshHub/SelectionOfClothes", ReplyAction="http://tempuri.org/IServicePoshHub/SelectionOfClothesResponse")]
        System.Threading.Tasks.Task SelectionOfClothesAsync(string sample, int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicePoshHub/Member")]
        void Member(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicePoshHub/Member")]
        System.Threading.Tasks.Task MemberAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicePoshHub/BlockUser")]
        void BlockUser(string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicePoshHub/BlockUser")]
        System.Threading.Tasks.Task BlockUserAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePoshHubCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePoshHub/SelectionOfClothesCallBack", ReplyAction="http://tempuri.org/IServicePoshHub/SelectionOfClothesCallBackResponse")]
        void SelectionOfClothesCallBack(int[] price, int[] quantity, int[] purchases, string[] name, string[] info, string[] image);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicePoshHub/MemberCallBack")]
        void MemberCallBack(string[] onlineUsersName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePoshHubChannel : PoshHub.ServicePoshHub.IServicePoshHub, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePoshHubClient : System.ServiceModel.DuplexClientBase<PoshHub.ServicePoshHub.IServicePoshHub>, PoshHub.ServicePoshHub.IServicePoshHub {
        
        public ServicePoshHubClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicePoshHubClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicePoshHubClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePoshHubClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePoshHubClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int Connect(string name) {
            return base.Channel.Connect(name);
        }
        
        public System.Threading.Tasks.Task<int> ConnectAsync(string name) {
            return base.Channel.ConnectAsync(name);
        }
        
        public void Disconnect(int id) {
            base.Channel.Disconnect(id);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(int id) {
            return base.Channel.DisconnectAsync(id);
        }
        
        public void SelectionOfClothes(string sample, int id) {
            base.Channel.SelectionOfClothes(sample, id);
        }
        
        public System.Threading.Tasks.Task SelectionOfClothesAsync(string sample, int id) {
            return base.Channel.SelectionOfClothesAsync(sample, id);
        }
        
        public void Member(int id) {
            base.Channel.Member(id);
        }
        
        public System.Threading.Tasks.Task MemberAsync(int id) {
            return base.Channel.MemberAsync(id);
        }
        
        public void BlockUser(string name) {
            base.Channel.BlockUser(name);
        }
        
        public System.Threading.Tasks.Task BlockUserAsync(string name) {
            return base.Channel.BlockUserAsync(name);
        }
    }
}
